---
title: "data-query"
output: html_document
date: "2024-09-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, # show warnings
  message = FALSE, # show messages
  error = TRUE, # do not interrupt generation in case of errors,
  echo = TRUE  # show R code
)
```


```{r}
library(tidyverse) 
library(dplyr)
library(sf) 
library(terra)
library(raster)
library(arrow)
```

```{r}
obis_snapshot <- "obis_20240625.parquet"
```

```{r}
db <- open_dataset(obis_snapshot)
```

```{r}
library(stringr)
obis_filter_test <- db |>
  filter(!str_detect(flags, "DATE_IN_FUTURE")) |> 
  filter(!str_detect(flags, "DATE_BEFORE_MIN")) |> 
  filter(!str_detect(flags, "NO_COORD")) |> 
  filter(!str_detect(flags, "ZERO_COORD")) |> 
  filter(!str_detect(flags, "LON_OUT_OF_RANGE")) |> 
  filter(!str_detect(flags, "LAT_OUT_OF_RANGE")) |> 
  filter(!str_detect(flags, "NO_DEPTH")) |> 
  filter(!str_detect(flags, "ON_LAND")) |> 
  mutate(bath_obs_prop_min = minimumDepthInMeters/bathymetry) |>
  mutate(bath_obs_prop_max = maximumDepthInMeters/bathymetry) |>
  mutate(bathymetry = round(as.numeric(bathymetry), 0)) |>
  mutate(minimumDepthInMeters = round(as.numeric(minimumDepthInMeters), 0)) |>
  mutate(depth_diff = bathymetry - minimumDepthInMeters) |>
  mutate(depth_quality_category = ifelse(bath_obs_prop_min <= 1.05 & bath_obs_prop_min >= 0, "depth_good", "depth_bad")) |>
  group_by(bathymetry, minimumDepthInMeters, bath_obs_prop_min, bath_obs_prop_max, depth_quality_category) |>
  count() |> 
  collect()
```

```{r}
depth_category_sums <- obis_filter_test |>
  group_by(depth_quality_category) |>
  summarize(total_n = sum(n))
```



```{r}
zero_depth_test <- obis_filter_test |>
  filter(minimumDepthInMeters == 0)
```


```{r}
obis_filter_test |> 
  ggplot(aes(x = depth_diff, weight = n)) +
  geom_histogram() +
  labs(x = "depth diff (bath - depth)", y = "Weighted Count") +
  theme_minimal()
```

```{r}
library(stringr)
obis_qc_test <- db |>
  group_by(absence,dropped) |>
  count() |> 
  collect()
```

```{r}
obis_bathymetry <- db |>
  filter(flags == "{}") |> 
  mutate(bath_obs_prop_min = minimumDepthInMeters/bathymetry) |>
  mutate(bath_obs_prop_max = maximumDepthInMeters/bathymetry) |>
  filter(bath_obs_prop_min > 0) |>
  filter(bath_obs_prop_min < 1) |>
  filter(bath_obs_prop_max > 0) |>
  filter(bath_obs_prop_max < 1) |>
  mutate(bathymetry = round(as.numeric(bathymetry),0),
         minimumDepthInMeters = round(as.numeric(minimumDepthInMeters),0)) |>
  group_by(bathymetry, minimumDepthInMeters, bath_obs_prop_min, bath_obs_prop_max) |>
  count() |> 
  collect()
```

```{r}
obis_bathymetry_flag_filter_only <- db |>
  filter(flags == "{}") |> 
  mutate(bath_obs_prop_min = minimumDepthInMeters/bathymetry) |>
  mutate(bath_obs_prop_max = maximumDepthInMeters/bathymetry) |>
  mutate(bathymetry = round(as.numeric(bathymetry),0),
         minimumDepthInMeters = round(as.numeric(minimumDepthInMeters),0)) |>
  group_by(bathymetry, minimumDepthInMeters, bath_obs_prop_min, bath_obs_prop_max) |>
  count() |> 
  collect()
```

```{r}
obis_bathymetry_nofilter <- db |>
  mutate(bath_obs_prop_min = minimumDepthInMeters/bathymetry) |>
  mutate(bath_obs_prop_max = maximumDepthInMeters/bathymetry) |>
  mutate(bathymetry = round(as.numeric(bathymetry),0),
         minimumDepthInMeters = round(as.numeric(minimumDepthInMeters),0)) |>
  group_by(bathymetry, minimumDepthInMeters, bath_obs_prop_min, bath_obs_prop_max) |>
  count() |> 
  collect()
```

```{r}
obis_filter_test_2 <- obis_filter_test |> 
  filter(bath_obs_prop_min != Inf) |>
  filter(bath_obs_prop_min != -Inf) |>
  filter(bath_obs_prop_min >= 0) |>
  filter(bath_obs_prop_min <= 1)
```

```{r}
obis_filter_test_3 <- obis_filter_test |> 
  filter(depth_quality_category == "depth_good")
```

```{r}
obis_filter_test_3 |> 
  ggplot(aes(x = bath_obs_prop_min, weight = n)) +
  geom_histogram(binwidth = 0.02) +
  labs(x = "min_depth prop", y = "Weighted Count") +
  theme_minimal()
```

```{r}
obis_bathymetry |> 
  filter(bath_obs_prop_max != Inf) |>
  ggplot(aes(x = bath_obs_prop_max, weight = n)) +
  geom_histogram(binwidth = 0.02) +
  labs(x = "min_depth prop", y = "Weighted Count") +
  theme_minimal()
```

```{r}
obis_bathymetry |> 
  ggplot(aes(x = minimumDepthInMeters, weight = n)) +
  geom_histogram(binwidth = 200) +
  labs(x = "Depth", y = "Weighted Count") +
  theme_minimal()
```

```{r}
obis_bathymetry <- obis_bathymetry %>%
  mutate(zone = case_when(
    bathymetry < 200 ~ "coastal",
    bathymetry >= 200 & minimumDepthInMeters < 200 ~ "shallow",
    bathymetry >= 200 & minimumDepthInMeters > 200 & bath_obs_prop_min < 0.99 ~ "deep",
    bathymetry >= 200 & minimumDepthInMeters > 200 & bath_obs_prop_min >= 0.99 ~ "benthic"
  ))
```

```{r}
obis_zone_summary <- obis_bathymetry %>%
  group_by(zone) %>%
  summarise(total_n = sum(n, na.rm = TRUE))
obis_zone_summary$pct <- obis_zone_summary$total_n/sum(obis_zone_summary$total_n, na.rm = TRUE)
```

## ID
```{r}
obis_pub <- db |>
  group_by(dataset_id) |>
  count() |> 
  collect()
```

## GBIF dataset_id's
```{r}
nodes <- read_tsv("datasets.tsv") |>
  rename(dataset_id = id)
orgs <- read_tsv("datasets_orgs.tsv") |>
  rename(dataset_id = id) |>
  left_join(nodes)
```

## join dataset keys between obis and gbif
```{r}
nodes_classification <- read_csv("nodes_obs_classified.csv") |>
  dplyr::select(node_name, n, class)

node_obs <- nodes_classification |>
  group_by(class) |>
  summarise(n = sum(n)) |>
  arrange(-n) |>
  mutate(all = sum(n)) |>
  mutate(perc = n/all*100) |>
  arrange(-perc) |>
  ggplot(aes(x = class, y = perc)) + geom_col() + coord_flip()

```

## Map 
```{r}
obis_map <- db |>
  mutate(latitude = round(decimalLatitude,2), 
         longitude = round(decimalLongitude,2)) |> 
  #filter(year >1800) |>
  count(longitude, latitude) |> 
  collect()
```

```{r}
df_spatial <- obis_map |> 
  dplyr::filter(!is.na(latitude), 
         !is.na(longitude)) |> 
  st_as_sf(coords = c("longitude", "latitude"), 
           crs = "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m")
```

```{r}
library(raster)
ras_temp <-raster(xmn=-180, xmx=180, ymn=-90, ymx=90,
                  resolution=c(0.1,0.1), vals=NA)
global_plot_all <- rasterize(df_spatial, ras_temp, 
                         field = "n", fun='sum') 
#rm(df_spatial) #remove unnecessary data
rm(ras_temp) #remove unnecessary data
```

```{r global_plot, cache=TRUE}
crs <- "+proj=robin +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m" 
global_plot_all <- terra::rast(global_plot_all) 
global_plot <- global_plot_all * 1 # to deal with NAs in this dataset 
# reproject for viz
global_plot_r <- terra::project(global_plot, crs, mask=TRUE) 
# define color gradient
library(MetBrewer)
colors <- c("grey", met.brewer(name="Isfahan1",n=20,type="continuous"))
# take log for viz
terra::plot(log(global_plot_r,10), col = colors, axes = FALSE)
writeRaster(global_plot_r, "../data/panels/PanelA_data.tif", overwrite=TRUE)
```




